// Prints which classifier combinations have dedicated content and which fall
// back to the general multifamily track. Output is checked in as
// docs/COVERAGE.md (regenerate with `npm run coverage > docs/COVERAGE.md`).

import { ASSET_TYPES, OWNERSHIP, PERSONAS, PMS, SECONDARY_ASSET_TYPES, type CallState, type Entry } from '../src/data/schema.ts';
import { ENTRIES } from '../src/data/entries.ts';
import { matches, resolve, specificity } from '../src/engine/resolve.ts';

const dedicated = (state: CallState): Entry[] =>
  ENTRIES.filter((e) => e.kind !== 'discovery' && specificity(e.appliesTo) > 0 && matches(e.appliesTo, state));

const out: string[] = [];
const p = (s = '') => out.push(s);

p('# Content coverage by classifier');
p();
p('Generated by `npm run coverage`. "Dedicated" = entries tagged to that classifier value; everything else');
p('falls back to the general multifamily track. The full matrix leaves PMS unset.');
p();

const blank: CallState = { asset: null, persona: null, ownership: null, pms: null };

for (const [axis, values] of [
  ['asset', ASSET_TYPES],
  ['persona', PERSONAS],
  ['ownership', OWNERSHIP],
  ['pms', PMS],
] as const) {
  p(`## By ${axis}`);
  p();
  p('| Value | Dedicated entries | Opener | Status |');
  p('|---|---|---|---|');
  for (const v of values) {
    const ids = ENTRIES.filter((e) => e.appliesTo[axis] !== '*' && (e.appliesTo[axis] as readonly string[]).includes(v));
    const r = resolve({ ...blank, [axis]: v });
    const inferredOnly = ids.length > 0 && ids.every((e) => e.tagSource === 'inferred');
    const secondary = (SECONDARY_ASSET_TYPES as readonly string[]).includes(v) ? ' _(secondary, not a priority)_' : '';
    const discoveryOnly = ids.length > 0 && ids.every((e) => e.kind === 'discovery');
    const status =
      discoveryOnly
        ? '◐ **discovery cues only — needs a talk track**'
        : ids.length > 0
        ? inferredOnly
          ? '◐ inferred tags only — confirm'
          : '✓'
        : v === 'conventional'
          ? 'general track (this *is* the default)'
          : axis === 'pms'
            ? 'general (no PMS-specific content)'
            : '⚠️ **FALLBACK — needs content**';
    p(`| ${v} | ${ids.length ? ids.map((e) => '`' + e.id + '`').join(', ') : '—'} | \`${r.opener.id}\` | ${status}${secondary} |`);
  }
  p();
}

// Full matrix: which axes contribute dedicated content in each cell.
// A = asset-specific, P = persona-specific, O = ownership-specific.
const axesHit = (state: CallState) => {
  const d = dedicated(state);
  const tag = (axis: 'asset' | 'persona' | 'ownership', letter: string) =>
    d.some((e) => e.appliesTo[axis] !== '*') ? letter : '·';
  return tag('asset', 'A') + tag('persona', 'P') + tag('ownership', 'O');
};
p('## Full matrix');
p();
p('Each cell shows which classifiers contribute dedicated content: **A**sset, **P**ersona, **O**wnership (`·` = none,');
p('that slot is general track). Discovery cues are not counted. Student and senior rows never get an A; lease-up gets one from its capability note only.');
p();
p('| Asset / Persona | ' + OWNERSHIP.join(' | ') + ' |');
p('|---|' + OWNERSHIP.map(() => '---').join('|') + '|');
let noAsset = 0;
let total = 0;
for (const asset of ASSET_TYPES)
  for (const persona of PERSONAS) {
    const cells = OWNERSHIP.map((ownership) => {
      const c = axesHit({ asset, persona, ownership, pms: null });
      total++;
      if (c[0] === '·') noAsset++;
      return '`' + c + '`';
    });
    p(`| ${asset} / ${persona} | ${cells.join(' | ')} |`);
  }
p();
p(`${noAsset} of ${total} combinations have no asset-specific content (all conventional, student and senior cells).`);
p();

console.log(out.join('\n'));
